### ISSUE TITLE
Options / Subcommands

### ISSUE THREAD

**Issue by NewtTheWolf** [TSLARoadster/TypeScript-Discord.js-v14-Template#4]
how exactly do I work with options or subcommands?

because the template "ApplicationCommand.ts" does not support this

i'm trying to add an option to a command with `addStringOption`, but unfortunately it doesn't work

**Comment by TSLARoadster** [comment]
Oh, my bad I forgot to implement an example of those. But basically, most of the implementation has to be manual at the moment due to discord.js lacking official "support" for Subcommands. I will work on an update to this now to make it part of the ApplicationCommand template.

**Comment by NewtTheWolf** [comment]
that was fast with the answer O.o


how long do you think you need for the update?

**Comment by TSLARoadster** [comment]
I'll try to get it updated by the end of today :)

**Comment by NewtTheWolf** [comment]
can you post a comment again in this Issue when you are done? ^^

**Comment by TSLARoadster** [comment]
@NewtTheWolf should be fixed now with the latest commit with examples too. If there continue to be issues reopen the issue/create a new one.

**Comment by NewtTheWolf** [comment]
sorry to bother you again

How does it work now with the input options?

E.g.

```js
		.addStringOption((option) => {
			option.setName('message').setDescription('The message to reply with.');
		})
```

**Comment by TSLARoadster** [comment]
I'm not sure I understand the problem. Could you elaborate? If possible have an entire code block example that I can replicate.
